import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import { Anton, Cormorant, Inter, Montserrat } from "next/font/google"


const montserrat=Montserrat({ subsets: ["latin"],variable: "--font-monserat", })
const inter = Inter({ subsets: ["latin"],variable: "--font-inter", });
const anton=Anton({ subsets: ["latin"],weight:["400"],variable: "--font-anton", })
const cormorant=Cormorant({ subsets: ["latin"],variable: "--font-cormorant", })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${cormorant.variable} ${inter.variable} ${montserrat.variable} ${anton.variable}`}
      >
        <div className="w-screen flex flex-col overflow-hidden bg-gradient-to-b from-20 from-[#67938C] to-transparent">
          <Navbar/>
        {children}
        </div>
      </body>
    </html>
  );
}
